app:
  base_url: "https://joyce677.github.io/TrendRadar"
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true

crawler:
  request_interval: 1000
  enable_crawler: true
  use_proxy: false
  default_proxy: "http://127.0.0.1:10086"

report:
  mode: "daily"
  rank_threshold: 5

notification:
  enabled: true
  message_batch_size: 4000
  batch_send_interval: 1
  feishu_message_separator: "━━━━━━━━━━━━━━━━━━━"

  silent_push:
    enabled: false
    time_range:
      start: "20:00"
      end: "22:00"
    once_per_day: true
    push_record_retention_days: 7

  webhooks:
    feishu_url: ""
    dingtalk_url: ""
    wework_url: ""
